export const DEVICE_MODULE_IMAGES = {
  'LU-add-module': require('assets/imgs/devices-modules/LU-add-module.png'),
  'UU-add-module': require('assets/imgs/devices-modules/UU-add-module.png'),
  'LU-offline': require('assets/imgs/devices-modules/LU-offline.png'),
  'LU-online-no-plants': require('assets/imgs/devices-modules/LU-online-no-plants.png'),
  'LU-online-with-plants': require('assets/imgs/devices-modules/LU-online-with-plants.png'),
  'UU-offline': require('assets/imgs/devices-modules/UU-offline.png'),
  'UU-online-no-plants': require('assets/imgs/devices-modules/UU-online-no-plants.png'),
  'UU-online-with-plants': require('assets/imgs/devices-modules/UU-online-with-plants.png'),
  'LU-UU-offline': require('assets/imgs/devices-modules/LU-UU-offline.png'),
  'LU-UU-online-no-plants': require('assets/imgs/devices-modules/LU-UU-online-no-plants.png'),
  'LU-UU-online-with-plants': require('assets/imgs/devices-modules/LU-UU-online-with-plants.png'),
  'LU-UU-connecting': require('assets/imgs/devices-modules/LU-UU-connecting.png'),
  'LU-UU-wifi': require('assets/imgs/devices-modules/LU-UU-wifi.png'),
};
